# Generated by Django 4.2.11 on 2024-03-18 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_card_card_type_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_images'),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2034, 3, 16, 21, 42, 4, 710477, tzinfo=datetime.timezone.utc)),
        ),
    ]
