# Generated by Django 4.2.11 on 2024-03-18 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_card_image_alter_card_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_images'),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2034, 3, 16, 21, 48, 14, 593432, tzinfo=datetime.timezone.utc)),
        ),
    ]
