# Generated by Django 4.2.11 on 2024-03-18 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_remove_card_image_account_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2034, 3, 16, 22, 38, 50, 680481, tzinfo=datetime.timezone.utc)),
        ),
    ]
