# Generated by Django 4.2.11 on 2024-03-20 20:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0011_alter_card_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_time', models.TimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('payment_type', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('S', 'Successful'), ('D', 'Declined'), ('P', 'Pending')], default='P', max_length=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.card')),
            ],
        ),
    ]
